### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by 2xyo** [Xunius/markdown2zim#3]
It would be greate to support python3 :) 

```
$ python3 zim2markdown.py ~/Documents/test/00_test.txt -o h.md

# <readFile>: Open input file:
/home/2xyo/Documents/test/00_test.txt

# <readFile>: Reading lines...
Traceback (most recent call last):
  File "zim2markdown.py", line 1117, in <module>
    main(FILEIN,FILEOUT,args.verbose)
  File "zim2markdown.py", line 1081, in main
    text=tools.readFile(filein,verbose)
  File "/home/2xyo/Documents/markdown2zim/lib/tools.py", line 46, in readFile
    lines.append(deu(line))
  File "/home/2xyo/Documents/markdown2zim/lib/tools.py", line 13, in deu
    return text.decode('utf8','replace')
AttributeError: 'str' object has no attribute 'decode'

```

**Comment by lrq3000** [comment]
This can be closed as it's fixed in #5.
